#### load libraries

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(tximport))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(PCAtools))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(clusterProfiler))
source("/project/imoskowitz/shared/software/helper_functions/carlosFunc_3.R")
source("/project/imoskowitz/shared/software/helper_functions/rowr.R")

```

#### import data
```{r}
txi <- salmon_import("/project/imoskowitz/shared/sequencing.processed/161221_K00242_0162_AHH7HFBBXX-IM-MR-RS30/star_salmon")
```

#### import metadata
```{r}

metadata  <- load_metadata("/project/imoskowitz/shared/metasheets/sample_sheets/MR014_161221_K00242_0162_AHH7HFBBXX-IM-MR-RS30_Sample_metasheet_v18.xlsx")

metadata <- metadata[match(colnames(txi[[2]]), rownames(metadata)), ]


```

#### create DESeq2 object
```{r}
dds <- DESeqDataSetFromTximport(txi, metadata, design = ~ condition)
dds <- DESeq(dds)
vst <- varianceStabilizingTransformation(dds)
res <- get_deseq_results(dds, contrast="condition", 
treatment="CD1_E10_HT", control="CD1_E10_pSHF")

```

#### PCA and sample correlations
```{r}
pca <- assay(vst)
pca <- PCAtools::pca(pca, metadata = metadata, removeVar = 0.9)

PCAtools::biplot(pca, colby = "condition",
                legendPosition = "right",
                pointSize = 3,
                labSize = 3)

ggsave(filename = "pca_biplot_condition.pdf",
       plot = last_plot(),
       device = "pdf",
       width = 8, height = 5,
       path = "pdfs")
dev.off()

pdf(file = "pdfs/heatmap_sample_cor.pdf", height = 5, width = 8)
assay(vst) |>
  cor() |>
  pheatmap::pheatmap(scale = "none",
                     display_numbers = T,
                     annotation_row = metadata["condition"],
                     annotation_col = metadata["condition"])
dev.off()


```

#### plot volcano and save results
```{r}
gg_volcano3(res,
abs_lfc = 0,
p.cutoff = 0.05,
up.color = "darkseagreen",
down.color = "green") +
gg_geneLabel4(res,
gene_col = "gene_id",
colorText = "black",
plotGenes = c("Foxf1",'Gli1', 'Hhip', 'Ptch1')) +
theme_minimal(base_size = 16) +
annotate(
      geom = "text",
      x = c(-Inf, Inf),
      y = c(Inf, Inf),
      hjust = c(-0.5, 1.5),
      vjust = c(2, 2),
      label = c(nrow(subset(res, log2FoldChange < 0 & padj < 0.05)),
                nrow(subset(res, log2FoldChange > 0 & padj < 0.05))),
      size = 6
) +
ggtitle("E10.5 HT/E10 pSHF")
  
ggsave(filename = "pdfs/volcano_HT_pSHF_E10.5.pdf",
plot = last_plot(),
device = "pdf",
width = 5, height = 5)
dev.off()

x <- runGO(test.vector = subset(res, padj < 0.05 & log2FoldChange > 0)$gene_id,
univr_vector = res$gene_id,
ont = "BP",
organism = 'mouse',
simplify = TRUE)
    
plotGO(obj = x,
topTerms = 5,
muhcolor = "darkseagreen",
strWrap = 30,
barWidth = 0.5,
expandY = c(0.1,0)) +
theme_minimal(base_size = 16)
    
ggsave(filename = "pdfs/GO_BP_HT_pSHF_E10.5_v_E10_pSHF_up.pdf",
plot = last_plot(),
device = "pdf",
width = 7, height = 5)
dev.off()


y <- runGO(test.vector = subset(res, padj < 0.05 & log2FoldChange < 0)$gene_id,
univr_vector = res$gene_id,
ont = "BP",
organism = 'mouse',
simplify = TRUE)

plotGO(obj = y,
topTerms = 5,
muhcolor = "green",
strWrap = 30,
barWidth = 0.5,
expandY = c(0.1,0)) +
theme_minimal(base_size = 16)

ggsave(filename = "pdfs/GO_BP_HT_pSHF_E10.5_v_E10_pSHF_down.pdf",
plot = last_plot(),
device = "pdf",
width = 7, height = 5)
dev.off()

write.csv(res, "data/Table_DESeq2_HT_pSHF_E10.5_v_E10_pSHF.csv")

write.csv(
  data.frame(y),
  "data/Table_GO_BP_down_padj0.05.csv")

write.csv(
  data.frame(x),
  "data/Table_GO_BP_up_padj0.05.csv")

```

